name: example
dependencies:
  hive_ce: any
  meta: ^1.14.0
dev_dependencies:
  rexios_lints: ^17.0.2
  build_runner: ^2.5.4
  hive_ce_generator:
    path: ..
environment:
  sdk: ^3.9.0
dependency_overrides:
  hive_ce:
    path: ../../hive
  hive_ce_generator:
    path: ..
