name: hive_ce_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 2.3.3
homepage: https://github.com/IO-Design-Team/hive_ce/tree/main/hive_flutter

environment:
  sdk: ^3.4.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ^2.11.2
  path_provider: ^2.0.10
  path: ^1.8.2

dev_dependencies:
  test: ^1.21.1
  rexios_lints: ^17.0.2
  mockito: ^5.4.1
  build_runner: ^2.5.4
