name: hive_ce_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.0.0
homepage: https://github.com/IO-Design-Team/hive_ce/tree/main/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  hive_ce: ^2.4.0
  analyzer: ^6.5.0
  source_helper: ^1.1.0
  glob: ^2.1.2
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.17.11
  build_test: any
  build_runner: any
  rexios_lints: ^8.2.0
  json_serializable: ^6.8.0

dependency_overrides:
  hive_ce:
    path: ../hive
