name: hive_ce
description: Hive Community Edition - A spiritual continuation of Hive v2
version: 2.4.2
homepage: https://github.com/IO-Design-Team/hive_ce/tree/main/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.14.0
  crypto: ^3.0.0
  web: ^1.0.0

dev_dependencies:
  test: ^1.17.12
  mocktail: ^1.0.4
  rexios_lints: ^7.0.0
  path: ^1.7.0
  pointycastle: ^3.4.0
  build_runner: ^2.1.2
