name: hive_storage_benchmark
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  json_annotation: ^4.9.0
  hive_ce: any
  hive: ^4.0.0-dev.2
  isar: ^4.0.0-dev.14
  csv: ^6.0.0
  meta: ^1.14.0

dev_dependencies:
  rexios_lints: ^17.0.2
  # build_runner: ^2.5.4 # TODO: Fix this
  json_serializable: ^6.8.0
  hive_ce_generator: any

dependency_overrides:
  hive_ce:
    path: ../../hive
  hive_ce_generator:
    path: ../../hive_generator
  build: ^4.0.0
  source_gen: ^4.0.0
  analyzer: ^8.0.0
