name: hive_ce_inspector
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.7.0
  hive_ce: ^2.13.0
  two_dimensional_scrollables: ^0.3.3
  vm_service: ^15.0.0
  yaml: ^3.1.3
  devtools_extensions: ^0.4.0
  devtools_app_shared: ^0.4.0
  dtd: ^4.0.0

dev_dependencies:
  rexios_lints: ^17.0.2
  hive_ce_flutter: ^2.3.2
  test: ^1.26.3

dependency_overrides:
  hive_ce:
    path: ../hive

flutter:
  uses-material-design: true
